"""description of the changes

Revision ID: 178c2d19c110
Revises: f773c8bc8cd6
Create Date: 2024-05-21 10:26:10.318729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '178c2d19c110'
down_revision = 'f773c8bc8cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('libelle', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('categorie', sa.String(length=140), nullable=False))
        batch_op.drop_column('text')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('text', mysql.TEXT(), nullable=False))
        batch_op.drop_column('categorie')
        batch_op.drop_column('description')
        batch_op.drop_column('libelle')

    # ### end Alembic commands ###
